layout_spectrum: 1
color:
  saturation: 0.9628033
  lightness: 0.2240143
  brandStrength: 0.8064516
  brandColors:
    - '#0D0C11'
    - '#F3F8F4'
    - '#D2B283'
    - '#BD8107'
    - '#A34F07'
  rhythmicContrast: 0.9505072
typography_spectrum: 0.5358423
name: Johnandsonsoysterhouse.com
